name: Bug report
description: Report a bug in qBitController
labels: [ bug ]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: Explain the details of the bug.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste crash logs if there is a crash, and any other logs that can help to solve the bug.

  - type: input
    id: qbitcontroller-version
    attributes:
      label: qBitController version
      description: Enter the qBitController version you encountered the bug on.
    validations:
      required: true

  - type: input
    id: qbittorrent-version
    attributes:
      label: qBittorrent version
      description: Enter the qBittorrent version you encountered the bug on.
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android version
      description: Enter the Android version you were using when you encountered the bug.
    validations:
      required: true

  - type: textarea
    id: additional-details
    attributes:
      label: Additional details
