name: Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      sign-android:
        required: false
        type: boolean
        default: false
      disable-cache:
        required: false
        type: boolean
        default: false
    secrets:
      store-file-base64:
        required: false
      store-password:
        required: false
      key-alias:
        required: false
      key-password:
        required: false

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: ${{ inputs.disable-cache }}

      - name: Build project
        run: ./gradlew assembleFreeRelease
        env:
          QBITCONTROLLER_SIGN_RELEASE: ${{ inputs.sign-android }}
          QBITCONTROLLER_STORE_FILE_BASE64: ${{ secrets.store-file-base64 }}
          QBITCONTROLLER_STORE_PASSWORD: ${{ secrets.store-password }}
          QBITCONTROLLER_KEY_ALIAS: ${{ secrets.key-alias }}
          QBITCONTROLLER_KEY_PASSWORD: ${{ secrets.key-password }}

      - name: Rename & move APK file
        run: |
          if [ "${{ inputs.sign-android }}" = "true" ]; then
            apk_path=composeApp/build/outputs/apk/free/release/composeApp-free-release.apk
          else
            apk_path=composeApp/build/outputs/apk/free/release/composeApp-free-release-unsigned.apk
          fi
          mv "$apk_path" "qbitcontroller-${{ inputs.version }}-android.apk"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.sign-android && 'android' || 'android-unsigned' }}
          path: "qbitcontroller-${{ inputs.version }}-android.apk"

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: ${{ inputs.disable-cache }}

      - name: Generate Info.plist
        run: ./gradlew generateIosFiles

      - name: Setup latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build project
        working-directory: iosApp
        run: xcodebuild -scheme iosApp -configuration Release -sdk iphoneos CODE_SIGNING_ALLOWED=NO -derivedDataPath ./build build

      - name: Generate IPA
        working-directory: iosApp
        run: |
          mkdir -p Payload
          mv ./build/Build/Products/Release-iphoneos/qBitController.app Payload/
          zip -r "qbitcontroller-${{ inputs.version }}-ios.ipa" Payload

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned
          path: "iosApp/qbitcontroller-${{ inputs.version }}-ios.ipa"

  build-windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifactName: windows-x86_64
            arch: x86_64

          - os: windows-11-arm
            artifactName: windows-arm64
            arch: arm64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: ${{ inputs.disable-cache }}

      - name: Build project
        run: ./gradlew packageReleaseMsi

      - name: Rename & move artifact
        shell: bash
        run: mv composeApp/build/compose/binaries/main-release/msi/qBitController-*.msi "qbitcontroller-${{ inputs.version }}-windows-${{ matrix.arch }}.msi"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifactName }}
          path: "qbitcontroller-${{ inputs.version }}-windows-${{ matrix.arch }}.msi"

  build-linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifactName: linux-x86_64
            arch: x86_64

          - os: ubuntu-24.04-arm
            artifactName: linux-arm64
            arch: arm64

    runs-on: ${{ matrix.os }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: ${{ inputs.disable-cache }}

      - name: Build project
        run: ./gradlew bundleReleaseFlatpak

      - name: Rename & move artifact
        shell: bash
        run: mv composeApp/build/flatpak/qBitController.flatpak "qbitcontroller-${{ inputs.version }}-linux-${{ matrix.arch }}.flatpak"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifactName }}
          path: "qbitcontroller-${{ inputs.version }}-linux-${{ matrix.arch }}.flatpak"

  build-macos:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            artifactName: macos-arm64
            arch: arm64

          - os: macos-13
            artifactName: macos-x86_64
            arch: x86_64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: ${{ inputs.disable-cache }}

      - name: Build project
        run: ./gradlew packageReleaseDmg

      - name: Rename & move artifact
        run: mv composeApp/build/compose/binaries/main-release/dmg/qBitController-*.dmg "qbitcontroller-${{ inputs.version }}-macos-${{ matrix.arch }}.dmg"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifactName }}
          path: "qbitcontroller-${{ inputs.version }}-macos-${{ matrix.arch }}.dmg"
