name: Build Snapshot

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Extract version
        id: set-version
        run: |
          SHA="${{ github.event.pull_request.head.sha || github.sha }}"
          echo "version=${SHA::7}" >> $GITHUB_OUTPUT          

  build:
    needs: extract-version
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.extract-version.outputs.version }}
